projects:
  - name: "test"
    queuesDefault:
      notifyBase: "http://localhost:5000"
      notifyTimeout: 5
      retryTimes: 3
      retryDuration: 3
      NotifyMethod: "API"
    queues:
      - queueName: test
        notifyPath: "/test" 
        bindingExchange: "test_exchange"
        routingKey:
          - "test"
